== Overview

[quote,Leopold Kronecker]
____
Number theorists are like lotus-eaters - having tasted this food they can never give it up.
____

This chapter provides the necessary background information on why
chapter <<practicalsettings>>
recommended _cipher string B_.

We start off by explaining the structure of cipher strings in section
<<architecture>> (architecture) and
define PFS in <<pfs>>. Next we present _Cipher
String A_ and _Cipher String B_ in section
<<recommendedciphers>>.

This concludes the section on cipher strings. In theory, the reader
should now be able to construct his or her own cipher string. However,
the question why certain settings were chosen still remains. To answer
this part, we need to look at recommended keylengths, problems in
specific algorithms and hash functions and other cryptographic
parameters. As mentioned initially in section <<relatedPublications>>,
the ENISA cite:[ENISA2013], ECRYPT 2 cite:[ii2011ecrypt] and BSI cite:[TR02102]
reports go much more into these topics and should be consulted in addition.

We try to answer the questions by explaining issues with random number
generators (section <<rngs>>), keylengths (section <<keylengths>>),
current issues in ECC (section <<EllipticCurveCryptography>>), a note
of warning on SHA-1 (section <<sha>>) and some comments on Diffie
Hellman key exchanges (section <<dh>>). All of this is important in
understanding why certain choices were made for _Cipher String A and
B_. However, for most system administrators, the question of
compatibility is one of the most pressing ones. Having the freedom to
be compatible with any client (even running on outdated operating
systems) of course, reduces the security of our cipher strings. We
address these topics in section <<compatibility>>. All these sections
will allow a system administrator to balance his or her needs for
strong encryption with usability and compatibility.

Last but not least, we finish this chapter by talking about issues in
PKIs (section <<pkis>>), Certificate Authorities
and on hardening a PKI. Note that these last few topics deserve a book
on their own. Hence this guide can only mention a few current topics in
this area.


