== Further Research

The following is a list of services, software packages, hardware devices or
protocols that we considered documenting but either did not manage to document
yet or might be able to document later. We encourage input from the community.

.Further Protocols
|====
| DNSSec (mention BCPs) | DANE | Tor
| S/Mime (check are there any BCPs? ) | TrueCrypt, LUKS, FileVault | AFS
| Kerberos | NNTP | NTPs tlsdate
| Moxa , APC, und co... ICS | |
| rsyslog | tftp | (s)ftp(s)
| haproxy | |
|====

.Further Protocols (Network centric)
|====
| IPv6 security | |
| Wi-Fi, 802.1x | SIP | SRTP
| Kerberos | NNTP | NTPs tlsdate
| BGP / OSPF | LDAP | seclayer-tcp
| RADIUS (RADSEC) | racoon | strongswan
| l2tp | |
| Ethernet to serial | DSL modems |
| UPnP, natPmp | |
| HTTP Key Pinning (HTKP) | |
| Monitoring: SNMPv3 | |
|====

.Further Applications
|====
| Lync | Tomcat |
| Microsoft SQL Server | Microsoft Exchange |
| IBM HTTP Server | |
|====

.Commerical Network Equipment Vendors

Other ideas:

SAML federated auth providers footnote:[e.g., all the REFEDS folks
(https://refeds.org/), including InCommon
(http://www.incommon.org/federation/metadata.html
https://wiki.shibboleth.net/confluence/display/SHIB2/TrustManagement)]

Elastic Load Balancing
(ELB)footnote:[https://lists.cert.at/pipermail/ach/2014-May/001422.html]

[[sec:uncovered]]
=== Software not covered by this guide

telnet: Usage of telnet for anything other than fun projects is highly
discouraged

Puppet DB: A Proxy or a tunnel is recommended if it needs to be facing
public network
interfaces.footnote:[https://lists.cert.at/pipermail/ach/2014-November/001626.html]

rsync: Best use it only via SSH for an optimum of security and easiest
to maintain.


