== Links

https://www.iana.org/assignments/tls-parameters/tls-parameters.txt[IANA official list of Transport Layer Security (TLS) Parameters]

//broken
//SSL cipher settings:
//http://www.skytale.net/blog/archives/22-SSL-cipher-setting.html

https://www.imperialviolet.org/2010/12/04/ecc.html[Elliptic curves and their implementation (04 Dec 2010)]

https://arstechnica.com/information-technology/2013/10/a-relatively-easy-to-understand-primer-on-elliptic-curve-cryptography/[A (relatively easy to understand) primer on elliptic curve cryptography]

https://github.com/ioerror/duraconf[Duraconf, A collection of hardened configuration files for SSL/TLSservices (Jacob Appelbaum’s github)]

// certificate expired, replaced by direct link
//https://www.isecpartners.com/media/106031/ssl_attacks_survey.pdf
https://www.nccgroup.trust/globalassets/our-research/us/whitepapers/ssl_attacks_survey.pdf[Attacks on SSL a comprehensive study of BEAST, CRIME, TIME, BREACH, LUCKY 13 & RC4 Biases]

https://www.eff.org/https-everywhere/deploying-https[EFF How to deploy HTTPS correctly]

https://www.computerworld.com.au/article/46254/bruce_almighty_schneier_preaches_security_linux_faithful/?pp=3[Bruce Almighty: Schneier preaches security to Linux faithful (on not recommending to use Blowfish anymore in favor of Twofish)]

https://bugzilla.mindrot.org/show_bug.cgi?id=1647[Implement FIPS 183-3 for DSA keys (1024bit constraint)]

https://eprint.iacr.org/2013/734.pdf[Elliptic Curve Cryptography in Practice]

https://crypto.2013.rump.cr.yp.to/981774ce07e51813fd4466612a78601b.pdf[Factoring as a Service]

https://dankaminsky.com/2012/08/06/bo2012/[Black Ops of TCP/IP 2012]

https://www.youtube.com/watch?v=Z7Wl2FW2TcA[SSL and the Future of Authenticity, Moxie Marlinspike - Black Hat USA
2011]

https://www.enisa.europa.eu/publications/algorithms-key-sizes-and-parameters-report[ENISA - Algorithms, Key Sizes and Parameters Report (Oct.’13]

// shortlink only redirect to IBM Knowledge Center -> broken
//Diffie-Hellman Groups http://ibm.co/18lslZf

//https://datatracker.ietf.org/doc/rfc3526/
https://tools.ietf.org/html/rfc3526[Diffie-Hellman Groups standardized in RFC3526]

// broken
//ECC-enabled GnuPG per RFC6637  https://code.google.com/p/gnupg-ecc

https://www.cosic.esat.kuleuven.be/ecc2013/files/kenny.pdf[TLS Security (Survey + Lucky13 + RC4 Attack) by Kenny Paterson]

https://arxiv.org/abs/1309.7366v1[Ensuring High-Quality Randomness in Cryptographic Key Generation]

https://en.wikipedia.org/wiki/Ciphertext_stealing[Wikipedia: Ciphertext Stealing]

https://en.wikipedia.org/wiki/Malleability_(cryptography)[Wikipedia: Malleability (Cryptography)]

http://www.ciphersbyritter.com/GLOSSARY.HTM[Ritter’s Crypto Glossary and Dictionary of Technical Cryptography]


