// [discrete] macro hides headline from TOC.
[discrete]
== Acknowledgements

We would like to express our thanks to the following reviewers and people who
have generously offered their time and interest (in alphabetical order):

Brown, Scott +
Brulebois, Cyril +
Burghardt, Krzysztof +
Dirksen-Thedens, Mathis +
Dulaunoy, Alexandre +
Endres, Johannes +
Gühring Philipp +
Grigg, Ian +
Haslinger, Gunnar +
Horenbeck, Maarten +
Huebl, Axel +
Knecht, Pascal +
Koetter, Patrick Ben +
Kovacic, Daniel +
Lenzhofer, Stefan +
Lorünser, Thomas +
Maass, Max +
Mehlmauer, Christian +
Millauer, Tobias +
Mirbach, Andreas +
O’Brien, Hugh +
Pacher, Christoph +
Palfrader, Peter +
Pape, Tobias (layout) +
Petukhova, Anna (Logo) +
Pichler, Patrick +
Riebesel, Nicolas +
Roeckx, Kurt +
Roesen, Jens +
Rublik, Martin +
Schiffbauer, Marc +
Schosser, Andreas +
Schüpany, Mathias +
Schulze, Andreas +
Schwartzkopff, Michael +
Schwarz, René («DigNative») +
Seidl, Eva (PDF layout) +
Van Horenbeeck, Maarten +
Wagner, Sebastian («sebix») +
Zangerl, Alexander +

The reviewers did review parts of the document in their area of expertise; all
remaining errors in this document are the sole responsibility of the primary authors.

