The OpenPGP protocolfootnote:[https://tools.ietf.org/search/rfc4880]
defines a set of asymmetric- and symmetric encryption algorithms,
signature methods and compression protocols.
GnuPGfootnote:[https://gnupg.org/], a FOSS implementation of the OpenPGP
standard, is widely used for mail encryption.

GnuPG signs a message, encrypts it symmetrically and encrpts the
symmetric key and the hash with Bob’s public key asymmetrically.

Research on SHA-1 conducted back in
2005footnote:[https://www.schneier.com/blog/archives/2005/02/sha1_broken.html]
as well as the first practical successful collision in early
2017footnote:[https://shattered.io/] has made clear that collision
attacks are a real threat to the security of the SHA-1 hash function.
Since SHA-1 is defined as a must implementation by the OpenPGP
specification, GnuPG is still using it. Currently settings should be
adapted to preferably avoid using SHA-1.

When using GnuPG, there are a couple of things to take care of:

keylengths (see section #section:keylengths[[section:keylengths]])

randomness (see section #section:RNGs[[section:RNGs]])

preference of symmetric encryption algorithm (see section
#section:CipherSuites[[section:CipherSuites]])

preference of hash function (see section
#section:CipherSuites[[section:CipherSuites]])

Properly dealing with key material, passphrases and the web-of-trust is
outside of the scope of this document. The GnuPG
websitefootnote:[http://www.gnupg.org] has a good tutorial on GnuPG.

After 31 December 2017 GnuPG version 2.0.x is no longer supported and
shall not be used
anymorefootnote:[https://lists.gnupg.org/pipermail/gnupg-announce/2017q3/000413.html].
Use the new long term version 2.1 instead.

== Hashing

Avoid SHA-1 by preferring better hashing methods. GnuPG. Edit
$HOME/.gnupg/gpg.conf:

== Key Generation

Because of lack of forward secrecy #subsection:PFS[[subsection:PFS]] in
OpenPGP it is preferable to use large asymmetric keys for long term
communication protection. A RSA key of 4096 bits should provide enough
confidentiality for the next 10
yearsfootnote:[https://www.keylength.com].

The preferences parameters S9 to Z1 correspond to AES256, CAMELLIA256,
AES192, CAMELLIA192, AES, CAMELLIA128, TWOFISH, SHA512, SHA384, SHA256,
BZIP2, ZLIB and ZIP. The parameters 3DES, SHA-1 and uncompressed are set
automatically by GnuPG.

== ECC - Elliptic Curve Cryptography

Since the release of GnuPG version 2.1
end-2014footnote:[https://www.gnupg.org/faq/whats-new-in-2.1.html] ECC
is supported. Older versions though are still widely used therefore ECC
is not yet applicable in practice.
