== General server configuration recommendations

For servers, we mostly recommend to apply what’s proposed by the
__Peter’s manifesto__footnote:[https://github.com/stpeter/manifesto].

In short:

require the use of TLS for both client-to-server and server-to-server
connections

prefer or require TLS cipher suites that enable forward secrecy

deploy certificates issued by well-known and widely-deployed
certification authorities (CAs)

The last point being out-of-scope for this section, we will only cover
the first two points.

== ejabberd

=== Tested with Versions

ejabberd 14.12, Debian 7 Wheezy

ejabberd 14.12, Ubuntu 14.04 Trusty

ejabberd 15.03, Ubuntu 14.04 Trusty

ejabberd 16.01, Ubuntu 14.04 Trusty

=== Settings

ejabberd is one of the popular Jabber servers. In order to be compliant
with the manifesto, you should adapt your
configurationfootnote:[http://www.process-one.net/docs/ejabberd/guide_en.html]:

=== Additional settings

It is possible to explicitly specify a cipher string for TLS
connections.

Note that we are setting the SSL option `cipher_server_preference`. This
enforces our cipher order when negotiating which ciphers are used, as
the cipher order of some clients chooses weak ciphers over stronger
ciphers.footnote:[https://blog.thijsalkema.de/me/blog//blog/2013/09/02/the-state-of-tls-on-xmpp-3/]

Starting with version 15.03footnote:[Early versions seem to have a few
bugs - although officially supported, it did not work in tests with
version 15.06. Version 16.01 is confirmed to work.], it is possible to
use custom Diffie-Hellman-Parameters. This allows us to negotiate
stronger Diffie-Hellman-keys, and also helps us avoid problems with
using common Diffie-Hellman-Parameters.footnote:[https://weakdh.org] You
can generate your own parameter file by running:

....
openssl dhparam -out dhparams.pem 4096
....

By default, ejabberd provides an administration website (look for the
ejabberd_http module). Enable TLS protection for it like this:

=== Tested with Versions

Debian Wheezy 2.1.10-4+deb7u1

=== Settings

Older versions of ejabberd use a different configuration file syntax. In
order to be compliant with the manifesto, you should adapt your
configurationfootnote:[http://www.process-one.net/docs/ejabberd/guide_en.html]
as follows:

=== Additional settings

Older versions of ejabberd (latexmath:[$<$] 2.0.0) need to be
patchedfootnote:[http://hyperstruct.net/2007/06/20/installing-the-startcom-ssl-certificate-in-ejabberd/]
to be able to parse all of the certificates in the CA chain. Specifying
a custom cipher string is only possible starting with version 13.12 (see
configuration for version 14.12 above).

=== References

* http://www.process-one.net/en/ejabberd/docs/[The ejabberd
documentation: http://www.process-one.net/en/ejabberd/docs/]

=== How to test

https://xmpp.net is a useful website to test Jabber server
configurations.

== Chat privacy - Off-the-Record Messaging (OTR)

The OTR protocol works on top of the Jabber
protocolfootnote:[https://otr.cypherpunks.ca/Protocol-v3-4.1.1.html]. It
adds to popular chat clients (Adium, Pidgin...) the following properties
for encrypted chats:

Authentication

Integrity

Confidentiality

Forward secrecy

It basically uses Diffie-Hellman, AES and SHA1. Communicating over an
insecure instant messaging network, OTR can be used for end to end
encryption.

There are no specific configurations required but the protocol itself is
worth to be mentioned.

== Charybdis

There are numerous implementations of IRC servers. In this section, we
choose _Charybdis_ which serves as basis for
__ircd-seven__footnote:[https://dev.freenode.net/redmine/projects/ircd-seven],
developed and used by freenode. Freenode is actually the biggest IRC
networkfootnote:[http://irc.netsplit.de/networks/top10.php]. _Charybdis_
is part of the _Debian_ & _Ubuntu_ distributions.

== SILC

SILCfootnote:[http://www.silcnet.org/ and
https://en.wikipedia.org/wiki/SILC_(protocol)] is instant messaging
protocol publicly released in 2000. SILC is a per-default secure chat
protocol thanks to a generalized usage of symmetric encryption. Keys are
generated by the server meaning that if compromised, communication could
be compromised.

The protocol is not really popular anymore.
