[[sec:how-read-this]]
== How to read this guide

This guide tries to accommodate two needs: first of all, having a handy
reference on how to configure the most common services’ crypto settings
and second of all, explain a bit of background on cryptography. This
background is essential if the reader wants to choose his or her own
cipher string settings.

System administrators who want to copy & paste recommendations quickly
without spending a lot of time on background reading on cryptography or
cryptanalysis can do so, by simply searching for the corresponding
section in chapter
#chapter:PracticalSettings[[chapter:PracticalSettings]] (``Practical
recommendations'').

It is important to know that in this guide the authors arrived at two
recommendations: _Cipher string A_ and _Cipher string B_. While the
former is a hardened recommendation the latter is a weaker one but
provides wider compatibility. _Cipher strings A and B_ are described in
#section:recommendedciphers[[section:recommendedciphers]].

However, for the quick copy & paste approach it is important to know
that this guide assumes users are happy with _Cipher string B_.

While chapter #chapter:PracticalSettings[[chapter:PracticalSettings]] is
intended to serve as a copy & paste reference, chapter
#chapter:Theory[[chapter:Theory]] (``Theory'') explains the reasoning
behind _cipher string B_. In particular, section
#section:CipherSuites[[section:CipherSuites]] explains how to choose
individual cipher strings. We advise the reader to actually read this
section and challenge our reasoning in choosing _Cipher string B_ and to
come up with a better or localized solution.

= [ellipse, draw, minimum height=2em, text width=4.5em, text badly
centered, inner sep=0pt] = [diamond, draw,aspect=2, text width=10em,
text badly centered, node distance=8em, inner sep=0pt] = [rectangle,
draw,inner sep=0pt, text width=17em, text centered, rounded corners,
minimum height=4em] = [draw, very thick, -latex’] =[near
start,color=black]
